### ISSUE TITLE
Wrong bitmap files loaded and positions off

### ISSUE THREAD

**Issue by neoengineer** [bergdahl/CircuitPython_MagTag_Sensor_Example#1]
The code is loading the same bitmap (temperature) for all three icons. In addition, the positioning of the icons is not the same as the image of the running code on the Adafruit website.

**Comment by bergdahl** [comment]
Thanks for pointing that out. I updated the code to the release version.

**Comment by neoengineer** [comment]
Thanks for the fast response! I really like the example project for the MagTag and your clean coding style :) There are some minor issues running with the latest version of circuit python (7.1.1) due to changes in the displayio class behavior. I needed to change the pixel_shader to use the one specified in the bitmap class attribute. Still learning those classes... Thanks again for the great example!
